apiVersion: skaffold/v2alpha4
kind: Config
# Enforce SKaffold to use Jib
build:
# Generated artifact
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.VER}}"
  artifacts:
    # - image: saturn203/simple-api
    # - image: saturn203/simple-api
    - image: vehicle-fe

# Use jib
      jib:
        args:
        - -DskipTests


# Execute deployment.yml
deploy:
  kubectl:
    manifests:
      - k8s/vehicle-fe.yaml

profiles:
  - name: kind
    build:
      local:
         push: false
      artifacts:
       - image: vehicle-fe
         jib:
           args:
           - -DskipTests
           - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=kind"
    deploy:
      kubectl:
       manifests:
         - k8s/*.yaml
portForward:
- resourceType: deployment
  resourceName: vehicle-fe
  namespace: front
  port: 8009
  localPort: 8009