apiVersion: skaffold/v2alpha4
kind: Config
# Enforce SKaffold to use Jib
build: 
# Generated artifact
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.VER}}"
  artifacts:
   
    - image: vehicle-fe
     
# Use jib
      jib: 
        args: 
        - -DskipTests
       

# Execute deployment.yml
deploy:
  kubectl:
    manifests:
      - k8s/vehicle-fe.yaml

profiles:  
  - name: kind
    build:
      local:
         push: false
      artifacts:
       - image: vehicle-fe
         jib: 
           args:
           - -DskipTests
           - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=kind"
    deploy:    
      kubectl:
       manifests:
        - k8s/configmap/*.yaml
        - k8s/gateway/*.yaml
        - k8s/*.yaml
         
  