##############
### local
##############

server:
 port: 8009

 
spring:
  profiles: kind  

  

api:
  vehicle:     
    url: http://vehicle-api-svc.vehicle.svc.cluster.local
  common:    
    url: http://common-api-svc.common.svc.cluster.local
   
   
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"  

management:
  endpoints:
    web:
      base-path: /mon    ##default: actuator
      exposure:
        include: hystrix.stream,health,info
    
