##############
### local
##############

server:
 port: 8009

 
spring:
  profiles: local  

  

api:
  vehicle: 
    url: http://vehicle-api
  common:
    url: http://common-api

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/


    
