##############
### local
##############

server:
 port: 8009

 
spring:
  profiles: kind  

  redis:
    port: 6379
    host: host.docker.internal


  

api:
  vehicle:     
    # url: http://vehicle-api-svc.vehicle.svc.cluster.local
    url: http://host.docker.internal:8000/vehicle-api
      # url: http://host.docker.internal:9720
  common:    
    # url: http://common-api-svc.common.svc.cluster.local
    url: http://host.docker.internal:8000/common-api
      # url: http://host.docker.internal:9720
   
   
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"  

management:
  endpoints:
    web:
      base-path: /mon    ##default: actuator
      exposure:
        include: hystrix.stream,health,info
    
