##############
### local
##############

server:
 port: 8009

 
spring:
  profiles: local  

  

api:
  vehicle:     
    url: http://localhost:9001
  common:   
    url: http://locahost:9002
   
   
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"  

management:
  endpoints:
    web:
      base-path: /mon    ##default: actuator
      exposure:
        include: hystrix.stream,health,info
    
