apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: front
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush        5
        Daemon       Off
        Log_Level    info
        Parsers_File parsers_springboot.conf

    [INPUT]
        Name    tail
        Path    /logs/vehicle-fe-out.log
        Tag     vehicle-fe
        Multiline        on
        Parser_Firstline springboot
    [OUTPUT]
        Name    forward
        Match   *
        Host    host.docker.internal
        Port    24224
  parsers_springboot.conf: |-
    [PARSER]
        Name        springboot
        Format      regex
        Regex       /^(?<date>[0-9]+-[0-9]+-[0-9]+\s+[0-9]+:[0-9]+:[0-9]+.[0-9]+)\s+(?<log_level>[Aa]lert|ALERT|[Tt]race|TRACE|[Dd]ebug|DEBUG|[Nn]otice|NOTICE|[Ii]nfo|INFO|[Ww]arn?(?:ing)?|WARN?(?:ING)?|[Ee]rr?(?:or)?|ERR?(?:OR)?|[Cc]rit?(?:ical)?|CRIT?(?:ICAL)?|[Ff]atal|FATAL|[Ss]evere|SEVERE|EMERG(?:ENCY)?|[Ee]merg(?:ency)?)\s+(?<pid>[0-9]+)\s+---\s+\[(?<thread>.*)\]\s+(?<class_name>.*)\s+:\s+(?<message>.*)$/
        Time_Key    time
        Time_Format %Y-%m-%